### ISSUE TITLE
Change image of RNA composition to reflect fewer reads in the OE sample (sample A)

### ISSUE THREAD

**Issue by marypiper** [hbctraining/DGE_workshop_salmon#22]

**Comment by jihe-liu** [comment]
I suggest change the text as below too (after changing the image):
"In the example, imagine the sequencing depths are similar between sample A and sample B, and every gene except for gene DE presents similar expression level between samples. The counts in sample B would be greatly skewed by the DE gene, which takes up most of the counts. Other genes for Sample B would therefore appear to be less expressed than those same genes in Sample A."
