### ISSUE TITLE
add an instance of using save() and load()

### ISSUE THREAD

**Issue by rkhetani** [hbctraining/DGE_workshop_salmon#27]
Might be nice to have them save an object - e.g. save the `ego` object.

**Comment by marypiper** [comment]
Add as note

**Comment by rkhetani** [comment]
@marypiper - I have added this as a note right before this -> https://github.com/hbctraining/DGE_workshop_salmon/blob/master/lessons/10_functional_analysis.md#visualizing-clusterprofiler-results
