### ISSUE TITLE
Run through functional analysis

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/DGE_workshop_salmon#45]
Code was modified to use the AnnotationHub dataframe from the annotations lesson. Need someone to run through it and make sure it works.

I have done so once and put figures here: `Dropbox (Harvard University)/HBC Team Folder (1)/Teaching/Courses/DGE_salmon/`

**Comment by jihe-liu** [comment]
Most figures are different right now. I stored updated figures in the same folder, with file name starting with "Jihe". So far running pathview command line does not generate any image. Will look into it next week.
A few more questions:
- In which lesson do we download data "c2.cp.v6.0.entrez.gmt.txt"?
- biocLite("GSEABase") has been changed to BiocManager

**Comment by marypiper** [comment]
We are not actually going to change the images or link the GMT - the images are similar so we will keep as is and we want to walk through how to download the GMT.
