### ISSUE TITLE
apply -> map

### ISSUE THREAD

**Issue by rkhetani** [hbctraining/DGE_workshop_salmon#5]
Convert all uses of apply() to map()-
I have only noticed it here so far: https://github.com/hbctraining/DGE_workshop_salmon/blob/master/lessons/01_DGE_setup_and_overview.md#how-do-i-know-if-my-data-should-be-modeled-using-the-poisson-distribution-or-negative-binomial-distribution

**Comment by mistrm82** [comment]
Already being addressed: https://github.com/hbctraining/DGE_workshop_salmon/issues/15
