### ISSUE TITLE
FA - assess what impact changing AnnotationDbi to AnnotationHub

### ISSUE THREAD

**Issue by marypiper** [hbctraining/DGE_workshop_salmon#6]

**Comment by mistrm82** [comment]
Figures have been added to DropBox; they mostly look similar

`Dropbox (Harvard University)/HBC Team Folder (1)/Teaching/Courses/DGE_salmon/`

**Comment by mistrm82** [comment]
code has been changed to now use annotationhub (ahb). Will add an issue for someone to run through the code
